"""make gene symbol nullable

Revision ID: 1c2383310e44
Revises: e3de8d71d171
Create Date: 2026-09-12 15:28:31.968570

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c2383310e44"
down_revision: str | Sequence[str] | None = "e3de8d71d171"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("genes", "symbol", existing_type=sa.VARCHAR(length=64), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("genes", "symbol", existing_type=sa.VARCHAR(length=64), nullable=False)
    # ### end Alembic commands ###
