"""initial schema

Revision ID: 57cab40aacf9
Revises:
Create Date: 2026-08-26 20:19:39.308774

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57cab40aacf9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "DIFFERENTIAL_EXPRESSION",
                "ENRICHMENT",
                "CLUSTERING",
                "CROSSTALK",
                name="analysistype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "FAILED",
                name="analysisstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "triggered_via",
            sa.Enum("API", "ETL", name="triggeredvia", native_enum=False),
            nullable=False,
        ),
        sa.Column("result_reference", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "datasets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("accession", sa.String(length=64), nullable=False),
        sa.Column(
            "source",
            sa.Enum("GTEX", "GEO", name="datasetsource", native_enum=False),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("organism", sa.String(length=128), nullable=False),
        sa.Column("assay_type", sa.String(length=128), nullable=False),
        sa.Column("citation", sa.String(length=1024), nullable=True),
        sa.Column("license", sa.String(length=256), nullable=True),
        sa.Column(
            "ingestion_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("checksum", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_datasets_accession"), "datasets", ["accession"], unique=True)
    op.create_table(
        "genes",
        sa.Column("ensembl_gene_id", sa.String(length=32), nullable=False),
        sa.Column("symbol", sa.String(length=64), nullable=False),
        sa.Column("biotype", sa.String(length=64), nullable=True),
        sa.Column("chromosome", sa.String(length=16), nullable=True),
        sa.PrimaryKeyConstraint("ensembl_gene_id"),
    )
    op.create_index(op.f("ix_genes_symbol"), "genes", ["symbol"], unique=False)
    op.create_table(
        "crosstalk_modules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_run_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_crosstalk_modules_analysis_run_id"),
        "crosstalk_modules",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_table(
        "differential_expression_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_run_id", sa.Integer(), nullable=False),
        sa.Column("gene_id", sa.String(length=32), nullable=False),
        sa.Column("tissue", sa.String(length=128), nullable=False),
        sa.Column("log2_fold_change", sa.Float(), nullable=False),
        sa.Column("pvalue", sa.Float(), nullable=False),
        sa.Column("padj", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_run_id"],
            ["analysis_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["genes.ensembl_gene_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "analysis_run_id", "gene_id", "tissue", name="uq_de_result_run_gene_tissue"
        ),
    )
    op.create_index(
        "ix_de_result_tissue_padj",
        "differential_expression_results",
        ["tissue", "padj"],
        unique=False,
    )
    op.create_index(
        op.f("ix_differential_expression_results_analysis_run_id"),
        "differential_expression_results",
        ["analysis_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_differential_expression_results_gene_id"),
        "differential_expression_results",
        ["gene_id"],
        unique=False,
    )
    op.create_table(
        "samples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("dataset_id", sa.Integer(), nullable=False),
        sa.Column("tissue", sa.String(length=128), nullable=False),
        sa.Column("condition", sa.String(length=128), nullable=False),
        sa.Column("age_bracket", sa.String(length=32), nullable=True),
        sa.Column(
            "sex",
            sa.Enum("FEMALE", "MALE", "UNKNOWN", name="sex", native_enum=False),
            nullable=True,
        ),
        sa.Column("bmi_category", sa.String(length=32), nullable=True),
        sa.Column("qc_metrics", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_samples_condition"), "samples", ["condition"], unique=False)
    op.create_index(op.f("ix_samples_dataset_id"), "samples", ["dataset_id"], unique=False)
    op.create_index(op.f("ix_samples_tissue"), "samples", ["tissue"], unique=False)
    op.create_table(
        "crosstalk_module_genes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("module_id", sa.Integer(), nullable=False),
        sa.Column("gene_id", sa.String(length=32), nullable=False),
        sa.Column("tissue", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["genes.ensembl_gene_id"],
        ),
        sa.ForeignKeyConstraint(
            ["module_id"],
            ["crosstalk_modules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("module_id", "gene_id", "tissue", name="uq_module_gene_tissue"),
    )
    op.create_index(
        op.f("ix_crosstalk_module_genes_gene_id"),
        "crosstalk_module_genes",
        ["gene_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_crosstalk_module_genes_module_id"),
        "crosstalk_module_genes",
        ["module_id"],
        unique=False,
    )
    op.create_table(
        "expression_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sample_id", sa.Integer(), nullable=False),
        sa.Column("gene_id", sa.String(length=32), nullable=False),
        sa.Column("raw_count", sa.Float(), nullable=True),
        sa.Column("normalized_value", sa.Float(), nullable=False),
        sa.Column(
            "unit",
            sa.Enum("TPM", "DESEQ2_NORMALIZED", name="expressionunit", native_enum=False),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["gene_id"],
            ["genes.ensembl_gene_id"],
        ),
        sa.ForeignKeyConstraint(
            ["sample_id"],
            ["samples.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sample_id", "gene_id", name="uq_expression_sample_gene"),
    )
    op.create_index(
        op.f("ix_expression_values_gene_id"), "expression_values", ["gene_id"], unique=False
    )
    op.create_index(
        op.f("ix_expression_values_sample_id"), "expression_values", ["sample_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expression_values_sample_id"), table_name="expression_values")
    op.drop_index(op.f("ix_expression_values_gene_id"), table_name="expression_values")
    op.drop_table("expression_values")
    op.drop_index(op.f("ix_crosstalk_module_genes_module_id"), table_name="crosstalk_module_genes")
    op.drop_index(op.f("ix_crosstalk_module_genes_gene_id"), table_name="crosstalk_module_genes")
    op.drop_table("crosstalk_module_genes")
    op.drop_index(op.f("ix_samples_tissue"), table_name="samples")
    op.drop_index(op.f("ix_samples_dataset_id"), table_name="samples")
    op.drop_index(op.f("ix_samples_condition"), table_name="samples")
    op.drop_table("samples")
    op.drop_index(
        op.f("ix_differential_expression_results_gene_id"),
        table_name="differential_expression_results",
    )
    op.drop_index(
        op.f("ix_differential_expression_results_analysis_run_id"),
        table_name="differential_expression_results",
    )
    op.drop_index("ix_de_result_tissue_padj", table_name="differential_expression_results")
    op.drop_table("differential_expression_results")
    op.drop_index(op.f("ix_crosstalk_modules_analysis_run_id"), table_name="crosstalk_modules")
    op.drop_table("crosstalk_modules")
    op.drop_index(op.f("ix_genes_symbol"), table_name="genes")
    op.drop_table("genes")
    op.drop_index(op.f("ix_datasets_accession"), table_name="datasets")
    op.drop_table("datasets")
    op.drop_table("analysis_runs")
    # ### end Alembic commands ###
