"""add source_sample_id to samples

Revision ID: e3de8d71d171
Revises: dac8c2535b09
Create Date: 2026-09-12 15:16:29.541317

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e3de8d71d171"
down_revision: str | Sequence[str] | None = "dac8c2535b09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("samples", sa.Column("source_sample_id", sa.String(length=64), nullable=True))
    op.create_unique_constraint(
        "uq_sample_dataset_source_sample_id", "samples", ["dataset_id", "source_sample_id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_sample_dataset_source_sample_id", "samples", type_="unique")
    op.drop_column("samples", "source_sample_id")
    # ### end Alembic commands ###
